spring.application.name=ecommerce

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=1234

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080

jwt.secret=9f8b3c7d2a6e4f1c8b5d9e0a7c3f6b1e4d8a2c7f9b5e1d3c6a8f0e2b4c7d9a1

